schemaVersion: 1.1.0
locale: "en"
groupings:
  - title: "Deploy dynamic group"
    variables:
    - tenancy_ocid
    - dynamic_group_name
    - dynamic_group_description
    - matching_rule

variables:
  tenancy_ocid:
    type: string
    title: Tenancy OCID
    description: The target compartment id where to create all resources
    required: true

  dynamic_group_name:
    type: string
    title: Dynamic Group Name
    description: The name of the dynamic group to create
    required: true

  dynamic_group_description:
    type: string
    title: Dynamic Group Description
    description: The description of the dynamic group to create
    required: true

  matching_rule:
    type: string
    title: Matching rule for the dynamic group
    description: The resources that are included in the dynamic group
    required: true
    default: "All {instance.id = 'ocid1.computecontainerinstance.oc1.eu-zurich-1.an5heljr2f6evfqajsdmjbbgknxqn6mvwn4soefkrbx6iukwlucwe7ljyroq'}"
